In [1]:
import pandas as pd
import numpy as np

import googlemaps
import gmaps

import settings

In [2]:
COL_RENAME_MAP = {
    'BlockNo': 'block_no',
    'LotNo': 'lot_no',
    'QualCode(s)': 'qual_codes',
    'PropLocation': 'location',
    'PropClass(s)': 'class',
    'SalesDate': 'sale_date',
    'SalePrice': 'sale_price',
    'NU\nCode': 'nu_code',
    '2017 Assmt\nTaxable': 'assessment_taxable_2017',
    '2017 Assmt\nExempt': 'exempt_2017',
    '2017 Assmt\nTotal': 'assessment_2017',
    '2017 Taxes\nTotal': 'taxes_2017',
    'VCS': 'vcs',
    'Year\nBuilt': 'year_built',
    'Design': 'design',
    'Square\nFootage': 'sq_ft',
    '2018 Assmt\nTaxable': 'assessment_taxable_2018',
    '2018 Assmt\nExempt': 'assessment_exempt_2018',
    '2018 Assmt\nTotal': 'assessment_2018',
    '2018 Taxes\nEstimated': 'taxes_2018',
}

gm = googlemaps.Client(key=settings.GMAPS_API_KEY)
gmaps.configure(api_key=settings.GMAPS_API_KEY)

In [3]:
df = pd.read_csv('data/jc-assessment.csv', low_memory=False).rename(index=str, columns=COL_RENAME_MAP)

df['change_pct'] = df['taxes_2018'] / df['taxes_2017']
df['change_dollars'] = df['taxes_2018'] - df['taxes_2017']

In [4]:
df

,block_no,lot_no,qual_codes,location,class,sale_date,sale_price,nu_code,assessment_taxable_2017,exempt_2017,...,vcs,year_built,design,sq_ft,assessment_taxable_2018,assessment_exempt_2018,assessment_2018,taxes_2018,change_pct,change_dollars
0,12609.0,00002 01,NaN,367 FIRST ST.,2,41719,1.0,4,865400,NaN,...,DTVL,2016.0,Rowhouse,6716.0,2706600,NaN,2706600,43846.92,0.649572,-23654.28
1,27503.0,11,C0108,108 E.SHEARWATER CT.,2,41974,1525000.0,26,597300,NaN,...,PL01,1988.0,Townhouse,4355.0,1558700,NaN,1558700,25250.94,0.541989,-21338.46
2,11101.0,9,NaN,323 FOURTH ST.,2,42516,10.0,3,437600,NaN,...,DTHC,2017.0,Rowhouse,7048.0,850500,NaN,850500,13778.10,0.403662,-20354.70
3,14106.0,22,NaN,249 GROVE ST.,2,37358,150000.0,,591500,NaN,...,DTVV,2016.0,Rowhouse,2496.0,1648900,NaN,1648900,26712.18,0.578975,-19424.82
4,27503.0,11.206,C0012,206-12 WEST SHEARWATER CT,2,35276,249000.0,26,383500,NaN,...,PL01,1996.0,Condo,2260.0,685400,NaN,685400,11103.48,0.371192,-18809.52
5,27503.0,11.207,C0017,207-17 WEST SHEARWATER CT,2,39022,650000.0,26,382900,NaN,...,PL01,1996.0,Condo,2260.0,694200,NaN,694200,11246.04,0.376547,-18620.16
6,4502.0,4,,54 SHERMAN AVE.,2,42352,1.0,24,307400,NaN,...,HTHT,1905.0,Duplex,2640.0,350000,NaN,350000,5670.00,0.236475,-18307.20
7,16203.0,1.01,,136 DELAWARE AVE.,2,42612,800000.0,NaN,369300,NaN,...,WSSP,1900.0,Colonial,1160.0,713300,NaN,713300,11555.46,0.401156,-17249.94
8,27503.0,11,C0103,103 E.SHEARWATER CT.,2,32149,1000000.0,NaN,504600,NaN,...,PL01,1988.0,Townhouse,3910.0,1438500,NaN,1438500,23303.70,0.592084,-16055.10
9,27503.0,11.100,C0081,100-81 SHEARWATER CT.,2,37582,394000.0,10,295200,NaN,...,PL01,1988.0,Condo,1740.0,537900,NaN,537900,8713.98,0.378447,-14311.62
10,12804.0,22,,268 MONTGOMERY ST.,2,42474,100.0,3,585000,NaN,...,DTVV,1920.0,Colonial,3040.0,1939800,NaN,1939800,31424.76,0.688686,-14205.24
11,11008.0,10,NaN,401 THIRD ST.,2,41648,220000.0,24,461400,NaN,...,DTVL,2016.0,Rowhouse,3820.0,1350800,NaN,1350800,21882.96,0.608042,-14106.24
12,11008.0,11,NaN,399 THIRD ST.,2,42628,1.0,3,461400,NaN,...,DTVL,2016.0,Rowhouse,3820.0,1350800,NaN,1350800,21882.96,0.608042,-14106.24
13,27503.0,11.100,C0084,100-84 SHEARWATER CT.,2,43067,362000.0,31,281500,NaN,...,PL01,1988.0,Condo,1660.0,502500,NaN,502500,8140.50,0.370747,-13816.50
14,20801.0,49,,264-266 EGE AVE.,2,32398,115000.0,NaN,275900,NaN,...,WSWS,1900.0,Colonial,2288.0,482800,NaN,482800,7821.36,0.363443,-13698.84
15,27503.0,11.109,C0012,109-12 E.SHEARWATER CT.,2,38499,995000.0,6,299300,NaN,...,PL01,1988.0,Condo,1760.0,602700,NaN,602700,9763.74,0.418230,-13581.66
16,27503.0,11.100,C0045,100-45 SHEARWATER CT.,2,32589,325500.0,NaN,262100,NaN,...,PL01,1988.0,Condo,1550.0,430400,NaN,430400,6972.48,0.341056,-13471.32
17,14101.0,7,,237 MONTGOMERY ST.,2,42474,100.0,3,535000,NaN,...,DTVV,1883.0,Duplex,2716.0,1766000,NaN,1766000,28609.20,0.685579,-13120.80
18,27503.0,11.101,C0034,101-34 E.SHEARWATER CT.,2,38657,546000.0,26,253400,NaN,...,PL01,1988.0,Condo,1495.0,411400,NaN,411400,6664.68,0.337193,-13100.52
19,14101.0,11,,227 MONTGOMERY ST.,2,41842,645000.0,9,395000,NaN,...,DTVV,1842.0,Rowhouse,3588.0,1117800,NaN,1117800,18108.36,0.587743,-12701.64
20,27503.0,11,C0104,104 E.SHEARWATER CT.,2,41141,2000000.0,26,443700,NaN,...,PL01,1988.0,Townhouse,3775.0,1353500,NaN,1353500,21926.70,0.633562,-12681.90
21,27503.0,11.111,C0011,111-11 EAST SHEARWATER CT,2,42682,635000.0,26,298800,NaN,...,PL01,1988.0,Condo,1760.0,668400,NaN,668400,10828.08,0.464597,-12478.32
22,11301.0,14,NaN,240 SECOND STREET,2,42474,1.0,3,450000,NaN,...,DTHC,1900.0,Duplex,2728.0,1408700,NaN,1408700,22820.94,0.650169,-12279.06
23,27503.0,11,C0105,105 E.SHEARWATER CT.,2,42159,1125000.0,26,381500,NaN,...,PL01,1988.0,Townhouse,2725.0,1112000,NaN,1112000,18014.40,0.605384,-11742.60
24,9908.0,33,C0002,336 SEVENTH ST.,2,42352,1487222.0,,415100,NaN,...,DT12,2015.0,Condo,2519.0,1279200,NaN,1279200,20723.04,0.640039,-11654.76
25,3804.0,7,,165 WEBSTER AVE.,2,42153,510000.0,NaN,392600,NaN,...,HTHT,1880.0,Duplex,3000.0,1185200,NaN,1185200,19200.24,0.626992,-11422.56
26,704.0,22,,93 IRVING ST.,2,42327,240000.0,,205000,NaN,...,HTWS,2017.0,Colonial,3670.0,290000,NaN,290000,4698.00,0.293809,-11292.00
27,9904.0,15,NaN,351 FIFTH ST.,2,41563,1.0,3,342300,NaN,...,DTVL,1887.0,Rowhouse,2112.0,961100,NaN,961100,15569.82,0.583152,-11129.58
28,9908.0,33,C0001,336 SEVENTH ST.,2,42348,1275000.0,7,356700,NaN,...,DT12,2015.0,Condo,1928.0,1034900,NaN,1034900,16765.38,0.602581,-11057.22
29,25503.0,9,,1904 KENNEDY BLVD.,2,38877,500000.0,,181200,NaN,...,GVJH,1920.0,Colonial,2023.0,214800,NaN,214800,3479.76,0.246205,-10653.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43515,12804.0,18,,260 MONTGOMERY ST.,2,42957,2564992.0,,190000,NaN,...,DTVV,1900.0,Colonial,3400.0,2271700,NaN,2271700,36801.54,2.483235,21981.54
43516,13903.0,8,NaN,293 YORK ST.,2,38083,1100000.0,,221700,NaN,...,DTVV,1925.0,Rowhouse,3774.0,2435700,NaN,2435700,39458.34,2.281805,22165.74
43517,11403.0,10,NaN,219 FIRST STREET,2,42088,1.0,3,180300,NaN,...,DTHC,1897.0,Rowhouse,4188.0,2249900,NaN,2249900,36448.38,2.591719,22384.98
43518,14106.0,31,NaN,10 BRIGHT ST.,2,30916,60000.0,,74900,NaN,...,DTVV,1873.0,Rowhouse,3288.0,1756700,NaN,1756700,28458.54,4.871203,22616.34
43519,11205.0,9,NaN,249 FIFTH ST.,2,35635,172500.0,,135000,NaN,...,DTHC,1870.0,Rowhouse,4016.0,2047100,NaN,2047100,33163.02,3.149385,22633.02
43520,13903.0,15,NaN,279 YORK ST.,2,40395,950000.0,7,220000,NaN,...,DTVV,1905.0,Rowhouse,3668.0,2488500,NaN,2488500,40313.70,2.349283,23153.70
43521,14202.0,3,NaN,155 GRAND ST.,2,42583,1300000.0,17,63800,NaN,...,DTPK,1925.0,Townhouse,2562.0,1752400,NaN,1752400,28388.88,5.704702,23412.48
43522,11205.0,7,NaN,253 FIFTH ST.,2,39042,715000.0,10,130000,NaN,...,DTHC,1905.0,Rowhouse,4016.0,2075100,NaN,2075100,33616.62,3.315249,23476.62
43523,12804.0,7,,93 MERCER ST.,2,42222,1.0,3,250000,NaN,...,DTVV,1900.0,Colonial,4788.0,2672300,NaN,2672300,43291.26,2.220065,23791.26
43524,14401.0,31,NaN,208 WARREN ST.,2,37645,1.0,10,133200,NaN,...,DTPK,1920.0,Townhouse,3893.0,2115500,NaN,2115500,34271.10,3.298597,23881.50
43525,13903.0,14,NaN,281 YORK ST.,2,37511,0.0,10,137000,NaN,...,DTVV,1905.0,Rowhouse,3404.0,2144800,NaN,2144800,34745.76,3.251522,24059.76
43526,14401.0,22,NaN,108 MORRIS ST.,2,42486,1875000.0,,100000,NaN,...,DTPK,1900.0,Townhouse,6200.0,1974900,NaN,1974900,31993.38,4.101715,24193.38
43527,14206.0,9,NaN,163 YORK ST.,2,35258,300000.0,,190000,NaN,...,DTPK,1900.0,Rowhouse,5176.0,2416400,NaN,2416400,39145.68,2.641409,24325.68
43528,11402.0,33,NaN,30 ERIE ST.,2,34808,45000.0,,91500,NaN,...,DTHC,1900.0,Rowhouse,3200.0,1948600,NaN,1948600,31567.32,4.423052,24430.32
43529,13903.0,11,NaN,287 YORK ST.,2,41845,1.0,3,225000,NaN,...,DTVV,1905.0,Rowhouse,3807.0,2593400,NaN,2593400,42013.08,2.393908,24463.08
43530,12705.0,22,,94 WAYNE ST.,2,42699,100.0,3,228000,NaN,...,DTVV,1880.0,Colonial,4968.0,2621700,NaN,2621700,42471.54,2.388188,24687.54
43531,13902.0,27,NaN,92 BRIGHT ST.,2,30827,87000.0,,165000,NaN,...,DTVV,1890.0,Colonial,5000.0,2321400,NaN,2321400,37606.68,2.922042,24736.68
43532,14101.0,43,NaN,272 BARROW ST.,2,38121,425000.0,,210000,NaN,...,DTVV,1852.0,Rowhouse,2808.0,2538900,NaN,2538900,41130.18,2.511000,24750.18
43533,14304.0,3,NaN,77 GRAND STREET,2,NaN,0.0,,350000,NaN,...,DTPK,1925.0,Rowhouse,7768.0,3229100,NaN,3229100,52311.42,1.916169,25011.42
43534,13903.0,18,NaN,48 BRIGHT ST.,2,36297,429750.0,,222000,NaN,...,DTVV,1898.0,Rowhouse,5664.0,2675900,NaN,2675900,43349.58,2.503441,26033.58
43535,12706.0,2,,203 COLUMBUS DR.,2,24398,1.0,4,160000,NaN,...,DTVV,1878.0,Rowhouse,4200.0,2399500,NaN,2399500,38871.90,3.114736,26391.90
43536,13904.0,3,NaN,71 BRIGHT ST.,2,35866,0.0,4,160500,NaN,...,DTVV,1925.0,Rowhouse,5084.0,2423800,NaN,2423800,39265.56,3.136477,26746.56
43537,13903.0,13,NaN,283 YORK ST.,2,41050,1160000.0,,165000,NaN,...,DTVV,1905.0,Rowhouse,3600.0,2477600,NaN,2477600,40137.12,3.118657,27267.12
43538,12802.0,22,,495 JERSEY AVE.,2,40105,100.0,1,142800,NaN,...,DTVV,1925.0,Rowhouse,3882.0,2403200,NaN,2403200,38931.84,3.495281,27793.44
43539,12809.0,18,NaN,483 JERSEY AVE.,2,34480,145000.0,,130000,NaN,...,DTVV,1900.0,Rowhouse,4390.0,2343800,NaN,2343800,37969.56,3.744533,27829.56
43540,11107.0,14,NaN,41 COLES ST.,2,39167,20000.0,,125000,NaN,...,DTHC,1885.0,Rowhouse,4800.0,2374200,NaN,2374200,38462.04,3.944825,28712.04
43541,14402.0,8,NaN,69 SUSSEX ST.,2,41314,1450000.0,,135000,NaN,...,DTPK,1925.0,Townhouse,4696.0,2447200,NaN,2447200,39644.64,3.764923,29114.64
43542,14401.0,20,NaN,104 MORRIS STREET,2,40379,1.0,4,125000,NaN,...,DTPK,1925.0,Rowhouse,4448.0,2421600,NaN,2421600,39229.92,4.023582,29479.92
43543,10008.0,28,C0305,299 PAVONIA AVE.,2,37098,350000.0,NaN,112900,NaN,...,WFDT,1890.0,Condominium,5350.0,2372400,NaN,2372400,38432.88,4.364298,29626.68
43544,14401.0,16,NaN,203 WASHINGTON ST.,2,42507,3125000.0,,175000,NaN,...,DTPK,1900.0,Townhouse,5972.0,3068900,NaN,3068900,49716.18,3.642211,36066.18

In [5]:
df['change_dollars'].describe()

count    43545.000000
mean       132.645318
std       3030.786323
min     -23654.280000
25%      -1507.200000
50%         38.880000
75%       1292.400000
max      36066.180000
Name: change_dollars, dtype: float64

In [6]:
df['change_pct'].describe()

count    43545.000000
mean         1.631901
std          2.069756
min          0.236475
25%          0.787615
50%          1.007176
75%          1.476841
max         23.076923
Name: change_pct, dtype: float64

In [15]:
df['address'] = df['location'].apply(np.char.strip) + ' Jersey City, NJ'

In [18]:
unique_addresses = set(list(df['address']))

In [20]:
ADDRESS_LAT_LNG_CACHE = {}

def get_lat_lng(addr):
    if addr in ADDRESS_LAT_LNG_CACHE:
        return ADDRESS_LAT_LNG_CACHE[addr]
    try:
        loc = gm.geocode(addr)[0]['geometry']['location']
    except Exception as e:
        print("Failed on address with exception:", addr, e)
        return None
    ADDRESS_LAT_LNG_CACHE[addr] = loc
    return loc

In [21]:
address_map = {}
for addr in unique_addresses:
    lat_lng = get_lat_lng(addr)
    if lat_lng is not None:
        address_map[addr] = lat_lng
    else:
        print("Failed to geocode", addr)

KeyboardInterrupt:

In [ ]:
#df['lat_lng'] = np.vectorize(get_lat_lng)(df['address'])
df['lat_lng'] = df['address'].apply(get_lat_lng)

In [ ]:
df

In [ ]:
df['lat'] = 
df['lng'] =

In [ ]:
locations = df['lat', 'lng']
weight = df['change_pct']
center_lat = df['lat'].mean()
center_lng = df['lng'].mean()

In [ ]:
heatmap_layer = gmaps.heatmap_layer(locations, weight, dissipating = True)
heatmap_layer.max_intensity = 5
heatmap_layer.point_radius = 15
# draw the heatmap into a figure
fig = gmaps.figure()
fig = gmaps.figure(center = [center_lat,center_lng], zoom_level=10)
fig.add_layer(heatmap_layer)